name: My Target Workflow
on:  
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          

      - name: Run Test
        run: mvn clean test
    
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Report
        run: |
          allure serve


